### ISSUE TITLE
Error: connect ECONNREFUSED 192.168.2.103:20060 when executing example.js

### ISSUE THREAD

**Issue by ghost** [forty2/bravia-simple-ip-control#1]
Hello, I've tried to run the example.js file, but I always get the following error:

Found a device: 3f1v2EKZHGYjqSjZ7G53sL
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 192.168.2.103:20060
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)

How can I use the commands from your project like changing volume?
I tried device.volume.set(value) in the example.js right after console.log in line 9.
Cannot get it to work, what do I do wrong?

**Comment by jpg0** [comment]
Go to Settings > Network > Home Network Setup
• Select IP Control
• Set Authentication to “Normal & Pre-shared Key”
• Set Simple IP control to “On”
